### ISSUE TITLE
When adding many extra note visual bugs start to occur

### ISSUE THREAD

**Issue by gittoaster** [matkatmusic/ChordieApp_IssueTracker#10]
Operating System version win10 1909
    Steps to reproduce the issue.
Start with say a bar chord across bottom 5 strings.  Then on A string move the fret up one note at a time until it's up near 12 fret or so.  Notes stop to replace the notes then all notes become held down, then all notes disappear but Keyboard view shows them all held down

    expected behavior
not sure honestly because this new feature seems to try to predict what I want but that is new as well.  I actually want to turn off this feature because it restricts me from laying things out (by trying to predict new fretting positions).  But that is a nice feature to have, too.
    behavior actually experienced.
see above
    crash log if you happen to have one.

**Comment by matkatmusic** [comment]
Can you show a video of this or some screenshots?

**Comment by gittoaster** [comment]
try this 
http://s000.tinyupload.com/download.php?file_id=13050310908862629349&t=1305031090886262934960912

**Comment by matkatmusic** [comment]
Alright, I'll figure out what should happen here.   The Fretboard only works with 6 notes max, and you have triggered more than 6 when you click.   I'm not trying to add a new way of showing all of the playable positions, nor am I trying to have it try to figure out what to do when you play more than 6 notes.  That is beyond the scope of this update.   

Maybe some kind of visual indication that the fretboard won't have a solution for ya?  I'm open to suggestions.

**Comment by gittoaster** [comment]
Hey Matt,
This is what I was referring to new behavior.. Kind of enjoying it but some times I just want to turn it off because I'm working in a specific area of the fretboard, and also use unison notes.  ty

http://s000.tinyupload.com/index.php?file_id=84762187793704245202

**Comment by matkatmusic** [comment]
You can attach files directly. For example:
![Screen Shot 2020-06-14 at 6 29 47 PM](https://user-images.githubusercontent.com/2929847/84609779-0e220400-ae6d-11ea-90cb-8da37116f2a7.png)

Please upload whatever you need to share directly.

**Comment by gittoaster** [comment]
can't upload video files

**Comment by gittoaster** [comment]
try this https://1drv.ms/v/s!AlWU8e7V8SIuhNpj7W5FaCO6djxWMQ?e=Qm3hIg ?

**Comment by matkatmusic** [comment]
> try this https://1drv.ms/v/s!AlWU8e7V8SIuhNpj7W5FaCO6djxWMQ?e=Qm3hIg ?

For that, you have to press 'shift' to add more notes on the same string. 
I'm still not sure what to do for the first issue you reported.  

> Maybe some kind of visual indication that the fretboard won't have a solution for ya? I'm open to suggestions.

If you have any opinions, let me know!

**Comment by gittoaster** [comment]
Hi Chuck
"I'm still not sure what to do for the first issue you reported."
I would suggest allowing unison notes to somehow stack, that seems to be what starts the issue.
If that were fixed, and maybe with another fix to allow more freely placing notes on fretboard (like previous releases) would be a solution.

**Comment by matkatmusic** [comment]
I'm still not fully understanding the issue.  This seems like it is four or five issues rolled into one. so I'm going to close this and request that you create a new one with steps for each separate thing that isn't behaving like you expect.  For example if you want it to allow clicking on unison notes, create an issue with specific steps showing how you're triggering notes, what you expect, and what actually happens.

However, the way it works currently is to send a note-on message when you click to the midi state, which then sends messages to the individual modules to repaint.  The midi state doesn't support multiple note-on's per pitch, so triggering multiple unison pitches in a fretboard won't happen with the current design.

**Comment by gittoaster** [comment]
I did, but you are closing them.

**Comment by matkatmusic** [comment]
The issues you are reporting are solved.  You have to hold Shift when you click notes to add them to the string.  I also said that clicking triggers note on which then causes the algorithm to try to figure out the fretboard that best matches all of the notes that are played.

Please look at the screenshots, videos, and emails I'm sending before you report the same issue multiple times.

**Comment by Morgen82** [comment]
OS: Win 7-64 Pro.
@matkatmusic said "Maybe some kind of visual indication that the fretboard won't have a solution for ya? I'm open to suggestions."
I suggest a 3 second popup text under the fretboard with something simple like:  6 note limit
