### ISSUE TITLE
Proposal - saving the position of separate windows for the next launch of the application

### ISSUE THREAD

**Issue by chordig** [matkatmusic/ChordieApp_IssueTracker#12]
I have such proposal - it would be very practical to use. When using the program with separate windows, would it be possible to save the position and maybe size of these windows so that the program can load it and start with the windows set up in such a way? That would be very useful.

**Comment by matkatmusic** [comment]
It does that already.  You have to switch to separate windows after it launches.  I might look at allowing it to restore separate windows after launch, but it might require major code surgery, which is beyond the feature set of this update.
