### ISSUE TITLE
Fretboard Preferences doesn't move to the front when you click on it in the menu.

### ISSUE THREAD

**Issue by Morgen82** [matkatmusic/ChordieApp_IssueTracker#17]
This might be working as intended but it means I have to go looking for it behind other windows.
It would be so much more elegant to pull it to the front when clicking on it in the menu.

Win 7-64 Pro

**Comment by Morgen82** [comment]
This might be how it was intended but I have to go look for it if it's behind some other window.

**Comment by Morgen82** [comment]
This might be working as intended but it means I have to looking for it behind other windows.

**Comment by matkatmusic** [comment]
Steps to reproduce?

**Comment by matkatmusic** [comment]
I had made this window **not** `always on top`, but it seems like that would be the preferred behavior? I'll switch to that and see if anyone else says anything.   You can't please everyone all the time, though...  Look for this change in the next build.
