### ISSUE TITLE
Actually its checking the selection above it.

### ISSUE THREAD

**Issue by Morgen82** [matkatmusic/ChordieApp_IssueTracker#18]
![Midi Input](https://user-images.githubusercontent.com/66924750/84607376-c8137300-ae61-11ea-980b-d22c00712311.PNG)

_Originally posted by @Morgen82 in https://github.com/matkatmusic/ChordieApp_IssueTracker/issues/16#issuecomment-643842349_

**Comment by Morgen82** [comment]
I don't know who you are but, Chordieapp@gmail.com asked me to beta test specifically because I am on Windows 7. I put Win 7-64 Pro on my issues reports to remind everyone of this with regard to this issue report.

Chordieapp@gmail wrote:
Would you mind trying the beta and seeing if it runs on it? I don't have access to windows 7 so I can't test.

On Sun, Jun 14, 2020, 2:57 PM Morgen 82 morgen82@gmail.com wrote:

Hi,

     Ditching support for Windows 7 is a mistake.

**https://www.statista.com/chart/8552/windows-7-is-still-the-desktop-os-king**/

Morgen Donner

**Comment by matkatmusic** [comment]
You already created one issue for this problem.  Stop creating new issues for the same problems.
