### ISSUE TITLE
Missing Notes

### ISSUE THREAD

**Issue by ghost** [matkatmusic/ChordieApp_IssueTracker#19]
After adding 12 strings to the guitar. There are only numbers but no notes to add.
<img width="127" alt="Screen Shot 2020-06-14 at 22 51 53" src="https://user-images.githubusercontent.com/66919419/84613736-f8730580-ae91-11ea-9d55-2646c418d90e.png">

**Comment by matkatmusic** [comment]
Hmm, you are beyond the allowed range of midi notes.  The range is 21 thru 21+88, since that is the range of the standard 88-key midi controller with no transposition active.  I'll figure out how to handle this.  Nice bug find!  💪💪

**Comment by matkatmusic** [comment]
Fixed in next build.
