### ISSUE TITLE
Piano keyboard does not stay lit to build chords like the fretboard does. 

### ISSUE THREAD

**Issue by jt3n1** [matkatmusic/ChordieApp_IssueTracker#20]
I am using a Mac book pro 2014 Mojave version 10.14.6

I am not sure if this is an "issue" or done on purpose. When I click a fret, it stays lit with the letter name and I can build out the chords. When I touch a key on the piano keyboard though, it does not stay lit, and I cannot build out chords. Like I said, Im not sure if that is an "issue" or something you have scheduled for a later update. Other than that, It seems to be working well.(I use it to record video tutorials with OBS, and logic, and even under that heavy computer usage, it is still performing well.) I will try and keep pushing it to see what happens.

**Comment by matkatmusic** [comment]
Scheduled for later!

**Comment by matkatmusic** [comment]
See this video: https://youtu.be/yBbtQyOTMTg and this video: https://youtu.be/WbosKb3bBEA
