### ISSUE TITLE
"One sec, calling home"

### ISSUE THREAD

**Issue by HelmutWindl** [matkatmusic/ChordieApp_IssueTracker#22]
What a frightening message. If this would not be a beta test I would uninstall this app immediately.
So, this app is calling home all the time. What does it share whith "at home"? Personal data? Usage data that I have not permitted to be shared? Other private information?

This is a NO GO!

BTW there might be a problem with the European data protection laws.

**Comment by matkatmusic** [comment]
It makes sure that you have authenticated, and downloads to latest chord definitions if you have.

The only thing it sends is your license key, your purchase email, and a unique hash representing your computer.  Calm down
