### ISSUE TITLE
Unable to install Chordie

### ISSUE THREAD

**Issue by edmccoll** [matkatmusic/ChordieApp_IssueTracker#24]
iMac 27 inch Late 2013
Processor 3.2 GHz Quad Core Intel Card
Memory 16Gb 1600 NHz DDR3

I attempted to install Chordie and I got the following message:
"ChordieApp" cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.

My only options are: 
1 Move to trash
2 Cancel

**Comment by matkatmusic** [comment]
See the FAQ on www.chordieapp.com

**Comment by edmccoll** [comment]
I am using Catalina, and that option is not available.
Here is a Screen Grab

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
