### ISSUE TITLE
can't create certain shapes higher on neck

### ISSUE THREAD

**Issue by gittoaster** [matkatmusic/ChordieApp_IssueTracker#25]
win10
I've been trying to make some regular guitar shapes eg. D string root around 5 fret and above.

https://1drv.ms/v/s!AlWU8e7V8SIuhNpmYKRuwP_MVTTbqg?e=OavGpT
expected.  note should be placed where I select on fretboard above 5 fret
actual
notes get lost and shape tries to revert to lower position
 please see video

**Comment by matkatmusic** [comment]
Did you enable being able to cycle through the fretboards and marking the preferred one in Fretboard Preferences?

**Comment by gittoaster** [comment]
No because if I did that for every chord it would be very annoying.  And often I don't plan ahead to where I am working.  
Often, guitar shapes don't have restrictions like you are suggesting.  Various techniques include open string positions higher on the neck, two handed technique which spans large distance on the neck such as a tap to hold.

**Comment by gittoaster** [comment]
Hey, did you notice that I entered 3 notes but only two actually persisted?

**Comment by matkatmusic** [comment]
I haven't looked at the video yet.  I will later tonight

**Comment by matkatmusic** [comment]
> Hey, did you notice that I entered 3 notes but only two actually persisted?

Ok, for this, you need to hold `shift` when you click to keep it from sending a note-off for any notes that are playing on the string you clicked on.

**Comment by matkatmusic** [comment]
> No because if I did that for every chord it would be very annoying. And often I don't plan ahead to where I am working.
> Often, guitar shapes don't have restrictions like you are suggesting. Various techniques include open string positions higher on the neck, two handed technique which spans large distance on the neck such as a tap to hold.

Good to know. 

I am not trying to support two-handed techniques right now.    I did have a feature in that Fretboard Preferences window where you could modify the rules that choose the 'first choice' fretboard.  But I took it out because no one would use it (I have waaay more keyboard players than guitarists using the app).  

![Screen Shot 2020-06-15 at 9 46 32 PM](https://user-images.githubusercontent.com/2929847/84732907-b90bee00-af51-11ea-8376-5656f807aad4.png)
I took it out.

**Comment by matkatmusic** [comment]
Ok, see this video for some commentary: 
https://www.dropbox.com/s/kh6gmzhft0x23cx/Mark%20as%20preferred.mp4?dl=0

**Comment by gittoaster** [comment]
> 
> 
> Ok, see this video for some commentary:
> https://www.dropbox.com/s/kh6gmzhft0x23cx/Mark%20as%20preferred.mp4?dl=0

Can you please just make it so I can select any 6 notes when working from a fretboard first perspective?  This new behavior really changes this from being useful for a guitar player to being something else.  
Finding lower fret positions a great and everything but it's not really helpful for advanced positions..

ty
