### ISSUE TITLE
I have no idea lol

### ISSUE THREAD

**Issue by matkatmusic** [matkatmusic/ChordieApp_IssueTracker#27]
![Screen Shot 2020-06-15 at 9 13 45 PM](https://user-images.githubusercontent.com/2929847/84731297-4ac52c80-af4d-11ea-83eb-8e60c0886102.png)

**Comment by matkatmusic** [comment]
The issue goes away if you reset the database.  Can't seem to replicate it once the database is reset.

**Comment by matkatmusic** [comment]
If anyone can replicate this behavior, I will gladly try to fix it.

**Comment by cfaia** [comment]
Seems to be linked with a large fretboard, for me anyway.
![Screen Shot 2020-06-16 at 08 36 08](https://user-images.githubusercontent.com/66990510/84739816-96f38980-afac-11ea-80ab-d5304e1ff753.jpg)

**Comment by matkatmusic** [comment]
Your screenshot doesn't appear to be showing the issue I showed in the first screenshot, with that rogue G on the lowest string in the wrong position.

**Comment by Morgen82** [comment]
OS: Win 7-64 Pro.  

I could not replicate rogue G and I tried.
