### ISSUE TITLE
Beta version does not run (Windows 10)

### ISSUE THREAD

**Issue by luigidarcio** [matkatmusic/ChordieApp_IssueTracker#3]
When starting app, I get error message  

The code execution cannot proceed because ucrtbased.dll was not found. Reinstalling the program may fix this problem. 

and clicking return again

The code execution cannot proceed because VCRUNTIME140D.dll was not found. Reinstalling the program may fix this problem. 

I have chordie versions 1.1.2 and 1.2.2c and those work fine on the same machine. 

So I cannot test the beta (for which I made a donation!)

**Comment by carlosagonzalez2** [comment]
There was another error reported at startup. The app does not start:

The code execution cannot proceed because uctbased.dll was not found.

**Comment by Pashkuli** [comment]
Windows 10 Pro June 2020 update ×64bit (latest up to now).
Run 'ChordieApp.exe' installation package.
BAM!!! Problems:

![ucrtbased](https://user-images.githubusercontent.com/66866528/84564823-9a90d180-ad5c-11ea-99c6-2621d29f36e3.jpg)
![MSVCP140D](https://user-images.githubusercontent.com/66866528/84564824-9b296800-ad5c-11ea-8742-5c85931b0a62.jpg)
![VCRUNTIME140D](https://user-images.githubusercontent.com/66866528/84564825-9bc1fe80-ad5c-11ea-89e8-71dd2c53b2d3.jpg)

I expected the installation to go smoothly.
_In my more than 25 years of managing and working on Windows based machines, I have never encountered such an issue on my machines._

**Comment by ricbennet** [comment]
> 
> 
> Windows 10 Pro June 2020 update ×64bit (latest up to now).
> Run 'ChordieApp.exe' installation package.
> BAM!!! Problems:
> 
> ![ucrtbased](https://user-images.githubusercontent.com/66866528/84564823-9a90d180-ad5c-11ea-99c6-2621d29f36e3.jpg)
> ![MSVCP140D](https://user-images.githubusercontent.com/66866528/84564824-9b296800-ad5c-11ea-8742-5c85931b0a62.jpg)
> ![VCRUNTIME140D](https://user-images.githubusercontent.com/66866528/84564825-9bc1fe80-ad5c-11ea-89e8-71dd2c53b2d3.jpg)
> 
> I expected the installation to go smoothly.
> _In my more than 25 years of managing and working on Windows based machines, I have never encountered such an issue on my machines._

I install chordie on 2 PC.
No problem on first PC.
Same problem as you on the second.

I think that the difference between these 2 PC is that on the first, Visual Studio is installed (and chordie run fine) on on the second visual studio is not installed (and chordier do not run).

I say that because the bug report <Fretboard "Debug Assertion Failed" bug #4>  describe MSCVP140D.DLL missing in the directory c:\........\microsoft visual studio\2017..etc.
I think that "microsoft visual studio\2017" is important

**Comment by gittoaster** [comment]
Same issue here

    Operating System version - win10 1909
    Steps to reproduce the issue. - launch chordie beta
    expected behavior - program should load
    behavior actually experienced. - error message related to MSVCP140D.dll, ucrtbased.dll, and VCRUNTIME140D.dll
    crash log if you happen to have one.

**Comment by Pashkuli** [comment]
> I install chordie on 2 PC.
> No problem on first PC.
> Same problem as you on the second.
> 
> I think that the difference between these 2 PC is that on the first, Visual Studio is installed (and chordie run fine) on on the second visual studio is not installed (and chordier do not run).
> 
> I say that because the bug report <Fretboard "Debug Assertion Failed" bug #4> describe MSCVP140D.DLL missing in the directory c:........\microsoft visual studio\2017..etc.
> I think that "microsoft visual studio\2017" is important

Hey, I see. I have Visual Studio Code installed. Actually I think it is the portable version (so it is not technically "installed"). Shame... because the Chordie v1.2.7 installs and works fine (has some bugs, at least it gets installed).
I'm not installing Visual Studio just because of Chordie. The problem is at Cordie's end.

btw, I've got installed both ×23 and ×64 bit of 'Microsoft Visual C++ redist' packages 2005 up to 2019.

**Comment by ricbennet** [comment]
I have installed "Microsoft Visual C++ redist' packages 2005 up to 2019" on my second PC (where visual studio is not installed) and the problem is yet here. Chordie desn't run.

**Comment by ricbennet** [comment]
> 
> 
> 
> Hey, I see. I have Visual Studio Code installed. Actually I think it is the portable version (so it is not technically "installed"). Shame... because the Chordie v1.2.7 installs and works fine (has some bugs, at least it gets installed).
> I'm not installing Visual Studio just because of Chordie. The problem is at Cordie's end.
> 
> btw, I've got installed both ×23 and ×64 bit of 'Microsoft Visual C++ redist' packages 2005 up to 2019.

I have installed "Microsoft Visual C++ redist' packages 2005 up to 2019" on my second PC (where visual studio is not installed) and the problem is yet here. Chordie desn't run.

**Comment by Pashkuli** [comment]
Chordie 1.2.3b , why u so dumb!?

**Comment by ricbennet** [comment]
> 
> 
> Chordie 1.2.3b , why u so dumb!?

:-)

Perhaps some compilation option forgotten...

**Comment by matkatmusic** [comment]
Hey thanks for reporting.   It's a Debug build, so you'll need to install that thing yourself.
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/7f22624f-d8c9-435b-a546-f1fc470bfb5b/vs2015-c-project-needs-ucrtbaseddll-how-to-install?forum=vssetup

**Comment by matkatmusic** [comment]
Actually, I found a setting I can change to get this included. 
![Screen Shot 2020-06-13 at 1 00 15 PM](https://user-images.githubusercontent.com/2929847/84577993-e603a980-ad75-11ea-9f71-c821e4e5dc7a.png)
Hang tight, I'll push out a new build shortly.

**Comment by carlosagonzalez2** [comment]
Hi Matkatmusic,
Do we get a free copy for beta testing? I recently purchased a copy of
Chordie I am kinda wishing now I should have waited for this new version.
Carlos

**Comment by matkatmusic** [comment]
> Hi Matkatmusic, Do we get a free copy for beta testing? I recently purchased a copy of Chordie I am kinda wishing now I should have waited for this new version. Carlos

Anyone who purchased will get this update for free after this beta testing period ends.  This is not a new version.  This is just an update.

**Comment by matkatmusic** [comment]
Fixed in latest build.
