### ISSUE TITLE
First note added above 5th fret doesn't stay, it changes

### ISSUE THREAD

**Issue by gittoaster** [matkatmusic/ChordieApp_IssueTracker#30]
win10
expected - select a fret anywhere on the fretboard and it should persist on/off manually
actual - selecting a fret above 5th fret chooses another note for me
settings - show all same notes on fret board off

**Comment by matkatmusic** [comment]
Please see the other issue you created where I added a video.

**Comment by gittoaster** [comment]
The bug is that this new behavior is not intuitive like before.  If you keep changing the app I purchased with new features that break it's core functionality, there is not much else I can do here.  Your video only provides a workaround for the broken core functionality. 
This 'magic notes' is the bug!!!

**Comment by gittoaster** [comment]
Your really saying you don't want to allow notes to be placed above the 5th fret?
