### ISSUE TITLE
Can't add these two notes without first being changed

### ISSUE THREAD

**Issue by gittoaster** [matkatmusic/ChordieApp_IssueTracker#32]
win10
expected - add these two notes should start forming a chord
actual - first note is changed after adding second
https://1drv.ms/v/s!AlWU8e7V8SIuhNppOW3v9pDeFT5_0Q?e=qzhTrY
settings default

**Comment by matkatmusic** [comment]
Instructions in an update email covered this 3 days ago. 
![Screenshot_20200616-094235](https://user-images.githubusercontent.com/2929847/84802669-c6f35a80-afb5-11ea-9d0e-38ce5b43d427.png)
