### ISSUE TITLE
Chordie will not install

### ISSUE THREAD

**Issue by edmccoll** [matkatmusic/ChordieApp_IssueTracker#33]
Tried to install following the directions in FAQ
"Go into System Preferences -> Security and Privacy -> General.   Set “Allow Apps Downloaded From” to “Anywhere” by clicking on the padlock in the lower left corner and authenticating.?

in macOS Catalina There is no option for "Anywhere" .  The only 2 options are: 
Allow apps downloaded from:
     App Store
     App Store and identified developers
I have "App Store and identified developers" checked.

I am still unable to install the Chordie beta

**Comment by matkatmusic** [comment]
https://www.macworld.co.uk/how-to/mac-software/mac-app-unidentified-developer-3669596/#toc-3669596-2

Scroll down to the "other ways to open"
