### ISSUE TITLE
Unison notes issue

### ISSUE THREAD

**Issue by gittoaster** [matkatmusic/ChordieApp_IssueTracker#34]
win10
actual
When I use unison notes it seems to break the program by causing variations between the keyboard and staff.   Subsequent notes pressed on the fretboard are added to the keyboard but not removed.  This causes some kind of build-up, which eventually causes all notes on the fretboard to disappear.
expected
i should be able to select or unselect unison notes on the fretboard then continue to add or remove notes as normal.

**Comment by gittoaster** [comment]
hi, since we got a new build already this seems like it's been mostly partially fixed.  I did manage to create it but not as it was before.

**Comment by matkatmusic** [comment]
Can you share a video showing EXACTLY how to replicate this behavior?  If you already did, please share the link.  Thanks!

**Comment by gittoaster** [comment]
Hi, I'll say that this video now might not be specifically what the original BR started, nonetheless here is the latest one.
https://1drv.ms/v/s!AlWU8e7V8SIuhNpv_WTEv3eUQRG6uQ?e=2qKPxE
by walking the note down a string the notes start to bug out.

**Comment by matkatmusic** [comment]
I'm trying to piece together what you're playing/clicking.  Would you mind recording what you did in the DAW to a midi file and emailing it?  I can't tell if you're shift-clicking notes or how you're adding them based on what I see happening to the piano roll but a midi file will make it perfectly clear what notes you sent to chordie. 

It should be easy to replicate how you're triggering it with the mouse, if you use the sustain pedal with your midi controller...

Right now, the fretboard module will not try to figure out a match for more than 6 midi notes.  You might be running into that limitation...

**Comment by matkatmusic** [comment]
@gittoaster please send me a midi file if you can.

**Comment by gittoaster** [comment]
Sorry, I must misunderstand.  I don't know how to output midi from the guitar fretboard to a midi out.

**Comment by matkatmusic** [comment]
I need you to send me which notes you're clicking on, on the fretboard, so I can replicate it here.  you can do that by recording some notes in the d a w and sending me a midi file that way or you can just send me a list.  When you click on the fretboard all it sends are note on messages to the internal processors.  It does not send a note off until you click a played note on the fretboard again.

**Comment by gittoaster** [comment]
Hi,
I can't replicate this issue with midi, only by interacting with the fretboard via the mouse left click.  In the video I can recreate it 10/10.
I can recreate using only two strings.
1) B string press high 20 fret 
2) G string start 20 fret then click down one fret and continue down one fret at a time.  When I get to C I notice there is now three notes held on the keyboard.  If I continue down the fret more notes are held and not released then eventually total bug-out.

**Comment by matkatmusic** [comment]
Let me know if this is what you're experiencing: https://youtu.be/ETUKWIsgJ_k

**Comment by gittoaster** [comment]
It is.  But I don't think you intend to have the note-buildup / disconnect between the fretboard and the other note displays.

**Comment by matkatmusic** [comment]
It's not a disconnect.  you are turning notes on via the fretboard, which sends note-on messages to the midi engine, which triggers the fretboard engine to figure out a matching fretboard for the set of on-notes, using some pre-defined rules to decide which fretboard to display out of the ones it computed.  As I said at the end of the video, It is doing what it is supposed to do.  However, what it is supposed to do might not be what you, the user, **expect** it to do when you click on the fretboard. 

I agree, there is room for improvement with this feature, but that won't happen between now and Friday when this update comes out. 

Right now, the functionality is:
```
when you click on the fretboard:
    if the string you're clicking on is already being played, 
         turn off that note being played by sending a note-off to the midi engine, and 
         turn on the new note by sending a note-on to the midi engine
```
then:
```
when the midi engine receives note on/off messages:
    wake up the fretboard engine to compute a new set of fretboard solutions for the input.
    pick the best choice from the solution set based on the sorting rules:
         1. "Prefer more matching notes"
         2. "Prefer less open strings"
         3. "Prefer lower played Frets"
         4. "Prefer smaller fret spread"
         5. "Prefer fretboard contains melody"
```

**Comment by gittoaster** [comment]
It's a disconnect even by your description because your saying that a note replaced should be turned off.  You've shown me that.

**Comment by matkatmusic** [comment]
I pushed out a new build last night. Are you still experiencing this @gittoaster 
If you are **not**, please report that it is resolved so I can close this issue.

**Comment by gittoaster** [comment]
No more issue with that now.  thank you.
