### ISSUE TITLE
Chord Name View on Mac/ Separate Windows Default

### ISSUE THREAD

**Issue by rjosephlaw** [matkatmusic/ChordieApp_IssueTracker#35]
The chord name view window can not be resized to a square shape

Is there a way to create separate windows as the default view so that when you launch it remembers that view as opposed to the single window view.

There are no shrink button labels on some of the Mac windows (ie the Yellow button that allows you to remove for example the Fretboard. I am using a piano, so I never use the fretboard.

Thank you. Cool app.

**Comment by matkatmusic** [comment]
You listed 3 issues in a single Issue.  
Please create ONE Issue for each problem next time. 
I shall reply to each one here: 

============================================================
```
The chord name view window can not be resized to a square shape
```
The window's proportions are fixed right now.  
If I allowed complete window resizing, some chord names would get cut off.  I have currently opted for a fixed window proportion so you always see the full chord names.  If more people request this I will look at it.   

![Screen Shot 2020-06-16 at 4 02 28 PM](https://user-images.githubusercontent.com/2929847/84836553-cd4ff980-afea-11ea-9955-9c7e72d8f174.png)

Please make a separate 'Feature Request' issue for not using fixed window proportions.  People can vote on it via the emoji button or by adding comments to the issue.  You can label it accordingly on the right side of the issue editor when you create it ("enhancement"). 

============================================================
```
There are no shrink button labels on some of the Mac windows (ie the Yellow button that 
allows you to remove for example the Fretboard. I am using a piano, so I never use 
the fretboard.
```
Disable it in Fretboard Preferences, under the menu.
![Screen Shot 2020-06-16 at 4 03 51 PM](https://user-images.githubusercontent.com/2929847/84836644-038d7900-afeb-11ea-82bb-093ad644ca5b.png)

============================================================
```
Is there a way to create separate windows as the default view so that when you launch 
it remembers that view as opposed to the single-window view.
```
This was already requested here: 
https://github.com/matkatmusic/ChordieApp_IssueTracker/issues/12
I have not looked yet at what would be required to enable this functionality.  As I said in that issue, if it requires major code surgery, it will not be in this update.
