### ISSUE TITLE
Mixed sharps and flats

### ISSUE THREAD

**Issue by dseixas** [matkatmusic/ChordieApp_IssueTracker#36]
I'm not sure this is an issue or an "as is" situation. I'm a music theory begginer.

I've have some trouble mixing flats and sharps in the same chord. Also IMHO it makes no sense adding sharps with a flat(s) signature.

Have a look at it on the attached screenshot.

![chordie-issue](https://user-images.githubusercontent.com/2110792/84895285-642bbd00-b0a2-11ea-91ce-127e3541e7ad.png)

Also, I'd love to have a selector to use flats or sharps on the C/Am scale...

**Comment by matkatmusic** [comment]
The spelling of notes is based on a spelling table per key.   
For example: `#1, b3, #4, b6, b7` in the key of C.  
If you're in the key of C, it will use the following scale to spell all the notes:  
`C C# D Eb E F F# G Ab A Bb B.`
When I first wrote chordie, this was my preferred way of seeing those accidentals as I was/am a horn player, not a piano player.   I hadn't thought about correcting the spelling based on what is actually played (harmonically speaking) at the time.
I have been thinking about what to do with regard to improving this part of chordie.   One idea that came into my head was to analyze the harmonic function relative to the key.  if the chord is anything other than one of the 7 diatonic chords (excluding the V/V), use the root of the chord as the key with which you determine which spelling table to use to spell the notes.   

For example: If you are in the key of C with spelling table [#1, b3, #4, b6, b7], and you play an E7b5b9
```
     if your spelling table for the key of E was [b2, b3, b5, b6, b7], 
         the spelling of the chord would be E G# D F Bb.
     if your spelling table for the key of E was [#1, #2, #4, #5, b7],
         the spelling of the chord would be E G# D E# A#
```
The idea of the spelling table comes from a feature in Finale which lets you customize how non-diatonic tones are initially spelled. 

I have the spelling table editor implemented in a version I'm not planning on releasing for a while.

**Comment by dseixas** [comment]
Hey thanks for the answer,

A little confusing for me because I'm a newbie in this music theory. 

I think the idea of using the tonic is a good one, but maybe adding a preference choice of "always use sharps/Always use flats/adhere to key signature/classic chordie" is also a good idea....

Just thinking out loud

**Comment by matkatmusic** [comment]
```
I think the idea of using the tonic is a good one, but maybe adding a preference choice of "always use sharps/Always use flats/adhere to key signature/classic chordie" is also a good idea....
```
good suggestion.  
I would probably do these choices:
- use Key Signature's Spelling Table
- Use Chord Root as Key
