### ISSUE TITLE
OSx fullscreen chordie app disappearing

### ISSUE THREAD

**Issue by dseixas** [matkatmusic/ChordieApp_IssueTracker#37]
I'm using the latest osX (Catalina). Also I'm using two screens and when I drag&drop from screen to screen chordie window disappears.

How to reproduce:
1. Open chordie in one screen
2. Open an app (word/chrome/...) in the other screen and fullscreen-ize it (it goes to the virtual desktop on the right)
3. Try to drag chordie from its screen to the other one.

It can't drag it because of the full-screen situation, but if you release the mouse button, chordie disappears. It's not a big deal but the first two times you go nuts trying to find it again (is enough to cmd+tab to it)

**Comment by matkatmusic** [comment]
If i understand correctly, you have 3 desktops total: 
Display 1 [Desktop 1]
Display 2 [Desktop 2, Chrome in Full Screen]

Chordie is on Desktop1.  
Which desktop do you then try to drag it to?  Desktop2 on Display 2?  or the desktop with full-screen Chrome?

**Comment by dseixas** [comment]
I'm trying to drag to Display 2 (with Chrome fullscreen)

**Comment by matkatmusic** [comment]
I'm on OS X 10.13.6 and it won't let me drag Chordie from a regular desktop to a desktop with a full-screen app.  Perhaps this is a new thing in Catalina?

**Comment by matkatmusic** [comment]
@dseixas I am unable to replicate this with ANY application.  I'll drag a non-full-screen application to my second monitor which has a full-screen application running on it, and the operating system won't let me finish the drag.  

I don't have any computers that can run anything higher than OS X 10.13.6, so I can't do anything about this bug if the full-screen functionality is something they changed in Catalina or Mojave.
