### ISSUE TITLE
chordie requires me to reregister each time I switch my windows display settings

### ISSUE THREAD

**Issue by lcalder** [matkatmusic/ChordieApp_IssueTracker#39]
I have a nvidia rtx 2080ti graphics card with 4 outputs. Two monitors are over my keyboard where I teach and two and over my desk where I work. All four are obviously connected to the same machine/PC running windows 10 pro 64-bit. I have two setups than enable two of the monitors and disconnects the other two depending on what I am doing.
Each time I run chordie after switching the setup it thinks I am running it on a new machine. The cpu (threadripper 3970x) and ram and motherboard and graphics cards and OS are all the same. Is there another way to verify the machine for copy protection besides checking the monitor configuration?

**Comment by matkatmusic** [comment]
Chordie doesn't check the monitor configuration.   that's not a unique characteristic of the machine. 
Are you testing the beta or the old v1.2.2c?

**Comment by lcalder** [comment]
I am using the latest and greatest beta issued I think 1 day ago...

I just went into it and it didn't ask for registration this time... but did this morning... I just built this machine two weeks ago. Before, when running this same scenario on  my laptop with your old version chordie would do the same thing by just moving the laptop five feet across the room and plugging into a different usb hub (with usb-midi attached as well different pair of 4k screens...)
Now the problem resurfaced in the newest version on a desktop pc that isn't being moved and has the monitors and usb-midi attached continuously between different configurations... only difference is the monitor configuration turns some monitors off and others on, but now I cannot recreate it. Maybe it needs a reboot too...

**Comment by matkatmusic** [comment]
```
now I cannot recreate it. Maybe it needs a reboot too...
```
So, are you no longer experiencing the issue?

**Comment by lcalder** [comment]
Yes just this morning. However I tried to recreate what I thought were the
casual factors and it didn't happen the second time. So it is lurking in
there somewhere. Do you have any ideas about what I might try as you know
what circumstances would cause the registration to feel the system had
changed?

**Comment by matkatmusic** [comment]
I'm not sure.  Would you mind sending me an email?  I might toss you a build with some extra stuff in it to help solve this.   I run Windows 10 inside Parallels, so my hardware configuration never changes.

**Comment by lcalder** [comment]
I sent my email via email so it's not published here. Did you get it?

**Comment by matkatmusic** [comment]
@lcalder I don't know your email address and get lots of emails, so i have no idea.  Please say something like "hey, it's @lcalder from github" or something so I know who you are when emailing about the beta.

**Comment by matkatmusic** [comment]
I pushed out a new build last night. Are you still experiencing this @lcalder 
If you are **not**, please report that it is resolved so I can close this issue.
