### ISSUE TITLE
Serial and email you entered is already registered to another computer

### ISSUE THREAD

**Issue by chordig** [matkatmusic/ChordieApp_IssueTracker#40]
From time to time (quite often) the application logs out and asks me to provide the serial and email again. I register the application still on the same computer.
It is a little bothersome to have to repeat it.

It happens in beta and in previous (not beta) version.

In the previous version of the application it says "It seems that the serial and email you entered is already registered to another computer. Would you like to de-register that computer to this serial/email and register this computer?" I always click "Yes", then I quit and run again the app.

In beta version happens the same. Only it says "Your credentials are already registered to another device. Would you like to deregister that device and register this device?". I click "Yes, register", then I quit and run again the app.

But after some time I must repeat this all.

**Comment by matkatmusic** [comment]
Are you on Windows or OS X?

**Comment by chordig** [comment]
> 
> 
> Are you on Windows or OS X?

Windows

**Comment by tiborkiss** [comment]
That happens to me with the latest paid version also. It may make sense to find out the cause, because it could be really annoying.

**Comment by chordig** [comment]
I don't know if it should be so.
I have already launched previous beta versions earlier.
But when I first launched the new today's beta on the same device it says "Your credentials are already registered to another device. Would you like to deregister that device and register this device?". I don't know if this should be the case because it is a new beta, but I prefer to mention it.

**Comment by matkatmusic** [comment]
@chordig let me know if this new build shows you that same message.

**Comment by matkatmusic** [comment]
@chordig any updates?
