### ISSUE TITLE
F# overlaps with G label.

### ISSUE THREAD

**Issue by tiborkiss** [matkatmusic/ChordieApp_IssueTracker#41]
F# and G pressed simultaneously causes overlapping the two labels.

![image](https://user-images.githubusercontent.com/531899/85197945-cecc3b00-b2e4-11ea-8efd-92bbc9f2f500.png)

Other key combination of white keys with the flats near by.

When I press F#, G, F then F# label goes up in the correct position, which is OK.

(One more note: Personally I would prefer to see the labels to not jump from one line to another, but keep there from on key press to release, therefore any note could appear in the main line or the upper line. Only the order of use will determine where it will be displayed.)

**Comment by matkatmusic** [comment]
That font looks like you're using the old version, not the beta.

**Comment by tiborkiss** [comment]
I downloaded again, but is the same.
My screen is a 4k screen without any magnification.

the file version is 1.2.3.0

**Comment by matkatmusic** [comment]
I'll look into it.  I don't have 4k screens here.  Are you on Windows or Mac?

**Comment by matkatmusic** [comment]
I can't recreate that here.  no matter how much i resize the separate windows keyboard (even making it tiny), it doesn't overlap like that.  I'm testing on a non-retina display, so when I try it out on my laptop, i'll let you know.  
![Screen Shot 2020-06-21 at 12 16 37 AM](https://user-images.githubusercontent.com/2929847/85218984-abd96f80-b354-11ea-8240-27336df5b4b5.png)

**Comment by matkatmusic** [comment]
Update: Verified on windows.  
Fixed in next build.
