### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by khatrus** [matkatmusic/ChordieApp_IssueTracker#42]
Hi! the app is great! the issue I found is that I can get any sound out of it. Im working in a Macbook pro 15" late 2013, 2.6 GHz Intel Core i7 16 GB High Sierra.

**Comment by chordig** [comment]
From ChordieApp site:
"Question: I'm not hearing any sound when I play on my midi controller
Answer: Chordie doesn’t generate any audio.  You need to use your DAW or a keyboard with sounds built in if you wish to hear what you’re playing. Chordie merely reads the midi data"
