### ISSUE TITLE
Agregar funciones (si es posible)

### ISSUE THREAD

**Issue by JorgeGaPa** [matkatmusic/ChordieApp_IssueTracker#43]
Buenas noches.
Varios de los errores que obtuve en esta versión beta ya los reportaron otros usuarios. Entonces, este no es un reporte de errores sino una petición de funciones (si es que es posible en este espacio):
1. A veces solo necesito la ventana del cifrado (Chord Name View) y la ventana del pentagrama (Manuscript View) para trabajar. Mi solicitud, en este caso, es que se pudieran minimizar las otras ventanas (Fretboard View and Piano Roll).
2. Y que se pudieran mantener en primer plano las ventanas que yo quiera. Casi siempre trabajo con Sibelius y Chordie al mismo tiempo y quisiera que las ventanas de Chordie, cuando trabajo con ventanas separadas, permanecieran en primer plano independientemente de que esté trabajando con otro software como Sibelius, Cubase, etc.

¡Gracias!

Trabajo con Windows 10 de 64 bits

**Comment by matkatmusic** [comment]
`Mi solicitud, en este caso, es que se pudieran minimizar las otras ventanas (Fretboard View and Piano Roll).`

"My request, in this case, is that the other windows (Fretboard View and Piano Roll) could be minimized."

I'll look into why the `minimize` button isn't showing up in the window title bars..
Thanks for requesting this.  It might not make it into this update, but I'll see what's involved in making it happen.

**Comment by JorgeGaPa** [comment]
¡Muchas gracias!
¿Y qué se puede hacer en cuanto a mantener las ventanas en primer plano?

**Comment by matkatmusic** [comment]
nothing.  don't make your notation software take up the whole screen.  

If you have any further questions or comments, please state them in English.  I don't speak Spanish and am relying on Google Translate. Thanks!

**Comment by JorgeGaPa** [comment]
I don't speak English either and I'm also relying the Google translator. I hope the translator is not giving us a bad move. Otherwise, thank you very much.

**Comment by JorgeGaPa** [comment]
When I work with separate windows and make the Manuscript View window small, the colors inside the notes are left out.

![Anotación 2020-06-22 190705](https://user-images.githubusercontent.com/67218601/85349436-acd8e100-b4bb-11ea-9eea-04979c0ec2e2.png)

**Comment by pigeond** [comment]
Hi there. I'm also interested in minimizing separate view windows, as it was possible in earlier versions. Thanks!
