### ISSUE TITLE
Can't make 6 note chords

### ISSUE THREAD

**Issue by gittoaster** [matkatmusic/ChordieApp_IssueTracker#44]
Hi, testing this chordie version by trying six note chords.

when I make 6 note chord with midi keyboard I only get 5 notes on the fretboard (worse than 1.2.2)

when I make six note chord with fretboard via mouse I run into the issue of notes building up then eventually notes disappearing/total bug out.

**Comment by matkatmusic** [comment]
Can you give me some input to test this out myself?   
Note names or a screenshot showing the keys on the midi keyboard pressed is fine.

**Comment by gittoaster** [comment]
It's pretty self-explanatory.  The new note handling makes drawing playable chords not work as described.
My thoughts on this below

The new behavior makes it difficult/impossible to use chordie to figure out/verify complex chords when working from the fretboard (which 1.2.2c does fantastically), mainly because finger positions are already known.  Let me try to explain.

I am using Chordie with guitar in my lap and one hand can reach to my computer mouse (so single click works well).

I think what you are doing is good for working from keyboard to guitar but not so much the other way (1.2.2c was good for that).
My suggestion is that when working with the fretboard the correct fingering is already a known variable, there is not a need to try to find a correct fingering.

I hope you can understand this and find a solution otherwise I won't be able to use chordie if the changes go through.  I will probably stay on 1.2.2c if possible.

**Comment by gittoaster** [comment]
For context this is what I am working on now
https://www.youtube.com/watch?v=h2DWEr338GM

**Comment by matkatmusic** [comment]
```
My suggestion is that when working with the fretboard the correct fingering is already a known variable, there is not a need to try to find a correct fingering.
```
this is a good suggestion.   
I'll see if I can come up with a 'mode' which disables the fretboard engine and only lets you trigger the fretboard by clicking on it.

**Comment by matkatmusic** [comment]
@gittoaster can you please send me an email so this feature can be spec'd out?  Just reply to your receipt from checkout...

**Comment by gittoaster** [comment]
Hi,
Latest version looks good so far with the exception of the latest bug report regarding open strings.
