### ISSUE TITLE
When I change to a key (other than default) Chordie will close unexpectedly...

### ISSUE THREAD

**Issue by lcalder** [matkatmusic/ChordieApp_IssueTracker#45]
I noticed Chordie just closing itself out of the blue twice yesterday while I was teaching and the only thing I remember doing differently was that I had selected D Major as the key signature the first time and the second time I was working in C-sharp Major. Each time this happened after an hour or more, so it might be hard to replicate. I tried today and I couldn't replicate it after about 10 minutes of playing pieces that are not in C-sharp with C-sharp selected as the key and still couldn't effect a crash...

**Comment by matkatmusic** [comment]
If you're on OS X, did you get a crash log?  Crash logs can be found here on OS X: 

open `Console.app` in `/Applications/Utilities/`
under `Reports`, navigate to `~/Library/Logs/`, and then `DiagnosticReports`
You'll see a bunch of reports from different applications.  Find the most recent report from ChordieApp.  it ends with `.crash`:

![Screen Shot 2020-06-22 at 11 42 19 PM](https://user-images.githubusercontent.com/2929847/85369515-17047c80-b4e2-11ea-9c7e-f1e77b8cb04a.png)

I don't know where crash logs on Windows go.

**Comment by lcalder** [comment]
I am on Windows 10... I tried opening the event viewer for windows but couldn't find anything chordie related in the ocean of data displayed. I am sure there must be a way to identify an application's error from these logs but I lack the understanding at this point.

**Comment by matkatmusic** [comment]
I'll see if I can generate a crash log in Parallels and put together instructions to find the crash log.

**Comment by matkatmusic** [comment]
@lcalder have you been able to experience this bug since you reported it?

**Comment by matkatmusic** [comment]
I pushed out a new build last night. Are you still experiencing this @lcalder 
If you are **not**, please report that it is resolved so I can close this issue.
