### ISSUE TITLE
Chordie keyboard sustain overlay sticks around for up to 30 seconds some times

### ISSUE THREAD

**Issue by lcalder** [matkatmusic/ChordieApp_IssueTracker#46]
Chordie keyboard sustain overlay sticks around for up to 30 seconds after sustain pedal is released. This can be recreated for example when one plays a chromatic scale of two or more octaves with the pedal on. I think it is trying to do a lookup on an increasingly complex "chord" and this takes it a long time. My machine is a ryzen threadripper 3970x and it can take up to 30 seconds to clear the sustain overlay, but I can imagine it might take a much longer time even on slower machines.
Maybe have a way for the lookup function to break out of the read loop on unrecognizable chords of a certain number of notes and no longer attempt to lookup additional notes with the sustain on...

**Comment by matkatmusic** [comment]
I experienced a similar lag a couple of days ago, but the problem went away when I made a release build.   The display is nice and responsive with the release build on both OS X and Windows.

Debug builds definitely experience this lag you speak of.
