### ISSUE TITLE
Crash program on pressing fret zero

### ISSUE THREAD

**Issue by gittoaster** [matkatmusic/ChordieApp_IssueTracker#5]
Win10 1909
When I press the fret zero after a (preferences reset to default) program crashes
expected - not to crash but place fret indicator

MS Visual C++ Runtime Library
Debug assertation
...
Line 1804
...
Expected Vector subscript out of range

![crash](https://user-images.githubusercontent.com/7898608/84580338-fa05d600-ad8a-11ea-9f6a-4a6c0f1cfc45.JPG)

**Comment by matkatmusic** [comment]
Fixed in latest build.
