### ISSUE TITLE
Chordie randomly requires re-registration.

### ISSUE THREAD

**Issue by lcalder** [matkatmusic/ChordieApp_IssueTracker#51]
Today I was teaching and suddenly my chordie windows disappeared from my outgoing feed. I use the "separate windows" option and then video capture within obs studio to grab the piano keys, as well as the chordie manuscript window and chord window. When I checked, it had gone back to single window as was requesting that I submit my registration details. After a resubmitted them, it didn't require me to restart as it normally does when this happens to me (this has happened to me about 4 times over the last two weeks). I clicked on "separate windows" but nothing happened until it clicked a couple of times. Then it seemed to work normally again.

**Comment by Morgen82** [comment]
OS: Win 7-64 Pro

In my case, always preceded by 'no internet connection' 
What I've been doing with each build
New Authentication and Registration and Restart

What I did this time:
Reset setting to default.
Reset ChordiApp Authentication
Use first beta license received, authenticated, registered and restarted.
 Works as expected.

**Comment by matkatmusic** [comment]
I pushed out a new build last night. Are you still experiencing this bug @Morgen82 
If you are not, please report that it is resolved so I can close this issue.

**Comment by Morgen82** [comment]
negative .  This build opens flawlessly.
