### ISSUE TITLE
Playing chords staccato - maybe add delay for note offs?

### ISSUE THREAD

**Issue by Yambam** [matkatmusic/ChordieApp_IssueTracker#52]
If you tend to play chords staccato (like it's often done in funk!) then the chords don't stay on the screen long enough to see/read it! So a small improvement/fix for that would be to post-pone the "events" caused by note-offs by for example (maybe with a setting), just a bit less than a second, 400 milleseconds maybe? So that way you could still see the notes/chords pressed until they "fade" about half a second after releasing them...

If you would add this feature, that would make the program even more fantastic than it already is! :)
Here's an example MIDI to test around with: https://imanuelhab.mooo.com/107%20-%20Synth%20sounds,%20a.mid

You can also hear (in this audio file's rendition) that the length of the "release" (and the reverb) is pretty long by the way, so it's a bit like that (adding a "release" time), but instead of in the audio, visually... ;D
https://imanuelhab.mooo.com/107%20-%20Synth%20sounds,%20a.ogg

**Comment by matkatmusic** [comment]
There is no clear way to solve this, as everyone has different preferences about how it should work. 
Also, this has the potential to create a ton of visual clutter and lose the real-time-ness of the app.

**Comment by Yambam** [comment]
I don't think it will cause clutter really... in that case "reverb" or release time (as the R in ASDR envelopes) would be clutter too, but in audio instead of visually!

I think it would be really nice if you considered adding it as a preference in the app though, like I suggested... like a "fading out" of the blue pressed note color... (instant fade out = 0 ms, the slider preference for note-off visual delay could be set to e.g. 400 ms for showing "funky" stabbed chords...)

I do staccato all the time, so it would be a no-go if it didn't show the chord on the screen after "just stabbing" it for a fraction of a second... Like I said I really like the whole app, but this seems pretty important to me...

The simplest solution I can think of is this:
For each incoming note-off event, don't remove that note from the chord directly yet (at least, when the setting for "Staccato Tolerance" is enabled, otherwise just remove the released note from the chord like normally). So instead of removing the note from the chord directly, add that just released note to a list, together with the timestamp for when that the note starts to "fade away".

So now you can divide the time by that "fade speed" preference, to get the fading blue notes' transparency/alpha values. And when the alpha becomes 0, finally remove the note from the chord... This is coming from a fellow programmer-musician, so I hope (and I do think so!) that my explanation makes sense to you! :)

**Comment by Yambam** [comment]
> 
> 
> There is no clear way to solve this, as everyone has different preferences about how it should work.
> Also, this has the potential to create a ton of visual clutter and lose the real-time-ness of the app.

@matkatmusic I forgot to quote you, so maybe you only get this notification? Either way, this is my proposed solution (just the last paragraph from my other reply):

... divide the time by the "fade speed" preference, to get the fading blue notes' transparency/alpha values. And when the alpha becomes 0, finally remove the note from the chord... This is coming from a fellow programmer-musician, so I hope (and I do think so!) that my explanation makes sense to you! :)
