### ISSUE TITLE
'Chord names' window with 'Whoops! Something went wrong!'

### ISSUE THREAD

**Issue by chordig** [matkatmusic/ChordieApp_IssueTracker#53]
Unfortunately, I don't know if this happens in the beta version, but more often I use the last paid version to be sure.
I prefer to mention this, however.
However, it sometimes happens that after some time of application operation in Separate windows mode in the "Chord names" window appears the message: "Whoops! Something went wrong! We've has already been notified, but feel free to send and email to chordieapp@gmail.com with more information. We'll help get you back up and running ASAP !! ". By this the chord names are not shown.
The internet (e.g. Skype connection) works without interruption at this time.
The rest of the windows work, e.g. Piano roll. When I turn the application off and on again, the chord name display works again.

**Comment by matkatmusic** [comment]
That message is not in the beta and the issue is resolved.
