### ISSUE TITLE
Windows in Separate windows mode cannot be minialized or closed

### ISSUE THREAD

**Issue by chordig** [matkatmusic/ChordieApp_IssueTracker#54]
In the current beta version on Windows, windows in Separate windows mode cannot be minimized or closed. Only the ChordieApp window has this capability - however, it only minimizes this one window. Especially the minimization option is always useful for every window.

**Comment by matkatmusic** [comment]
Duplicate of https://github.com/matkatmusic/ChordieApp_IssueTracker/issues/43
