### ISSUE TITLE
Separate View - Fretboard

### ISSUE THREAD

**Issue by romuloso** [matkatmusic/ChordieApp_IssueTracker#57]
Hi there, in latest version is View Separate Windows gone?? I loved using that in OBS. In build before this, still had an issue where I could not add fretboard as window capture in obs, but chordnames pianoroll and grandstaff 

Operating System version: Windows 10
Steps to reproduce the issue. Open Chordie - change view to separate windoes, try to window capture in OBS
expected behavior - 
behavior actually experienced. no fretboard as option (and no separate windows in newest version? :'(
crash log if you happen to have one.
![matkat window cap fret nogo](https://user-images.githubusercontent.com/67513441/85926336-d784ba00-b86c-11ea-9773-849f5539ddbd.JPG)

**Comment by romuloso** [comment]
found how to get separate view...but still having issues getting chordname view to appear nicely..may be able to solve on my own with resizing will keep working on it

**Comment by matkatmusic** [comment]
`[Chordie v1.2.2c.exe] Chordie Fretboard` is at the top of OBS menu for picking which window to capture.

Please explain `still having issues getting chordname view to appear nicely`

**Comment by romuloso** [comment]
Thanks for quick reply! Update: I solved it by hitting fit to screen/reset transform/stuff like that. Was an OBS issue not Chordie. Good luck with upcoming release, thanks for your work!

**Comment by matkatmusic** [comment]
Thanks for supporting the app @romuloso !
