### ISSUE TITLE
Usage of keys lighting up yellow on keyboard unclear - nothing happens

### ISSUE THREAD

**Issue by avdiem** [matkatmusic/ChordieApp_IssueTracker#6]
When hovering over the keyboard with the mouse, keys light up yellow. (See F in example below). When clicking on a key, nothing happens.

In previous Chordie version this behaviour was not there.

Usage is unclear. When clicked, should the corresponding note be displayed on Manuscript view, like when clicking a fret? Should note be played through MIDI out?

<img width="1422" alt="Screenshot 2020-06-14 at 11 22 10" src="https://user-images.githubusercontent.com/34418922/84589782-57546280-ae31-11ea-8598-7cf54e57c91c.png">

**Comment by matkatmusic** [comment]
Just checked.  Chordie v1.1.2 still has this.  Chordie v1.2.2c does not have this.   I'll disable it.  Thanks for reporting it!

**Comment by matkatmusic** [comment]
Fixed in next build.
