### ISSUE TITLE
Crashes saying no internet and ruins window capture in OBS

### ISSUE THREAD

**Issue by romuloso** [matkatmusic/ChordieApp_IssueTracker#60]
Crashes saying no internet and ruins window capture in OBS. I have ethernet connected with over 500 MB/s speed.
After hitting try again to connect to internet, all of the window captures in OBS are ruined. It considers Chordie Piano Roll to be the "best teaching tool you'll ever use" window. The Chord name view is much smaller than before when it asked for internet. Had a previous issue where chordie just stopped showing up, in the middle of recording a video, no error message or asking for internet connection this time. It also seems to take upwards of 30 seconds to start up as it's calling home. 

Operating System version - Windows 10. 32 GB RAM
Steps to reproduce the issue. Record in OBS with window captures, adjust size and position.
expected behavior - window captures stay intact even if internet gets confused 
behavior actually experienced - chordie shuts down without warning or says no internet, then the window captures are ruined and cannot be fixed.
Thanks!

**Comment by matkatmusic** [comment]
I am unable to replicate this.
