### ISSUE TITLE
Guitar Chords, no alternative fingerings shown

### ISSUE THREAD

**Issue by austinboat** [matkatmusic/ChordieApp_IssueTracker#61]
When I enter a chord on the fretboard, it will show the chord name but instead of something like "#1 of 82"  it always says "#1 of 1" until I reset the fretboard database.  As soon as I change a note, which changes the chord, it goes back to "#1 of 1" until I again press Reset Fretboard Database.  I did accidentally start using the app before reseting everything, but deleting and redownloading+installing didn't fix this.  Hopefully I'm not the only one with this problem.  Thanks for this app and all the fixes!

![Screen Shot 2020-06-29 at 11 59 32 PM](https://user-images.githubusercontent.com/61560256/86094321-34e35b80-ba65-11ea-9b7b-e5a528dac4aa.png)
![Screen Shot 2020-06-29 at 11 59 39 PM](https://user-images.githubusercontent.com/61560256/86094730-c5ba3700-ba65-11ea-8d77-2b05a202a3f3.png)

**Comment by austinboat** [comment]
also, not sure if this is a bug or not, but it seems intuitive that you should be able to click on the keyboard or staff to add or remove notes, the same as the fretboard.  At least when there's no midi detected, or maybe just in a different color than the midi readings?  just a thought !

**Comment by matkatmusic** [comment]
I hope this clarifies things:
https://youtu.be/tG6DMDqmbHs

clicking on the keyboard is planned for later: 
https://youtu.be/yBbtQyOTMTg
https://youtu.be/WbosKb3bBEA

**Comment by austinboat** [comment]
Hey thank you for the video!  With the latest patch the fretboard has been working great, thanks for the fix.  For my purposes it would be super helpful to have the option to instantly access the alternative voicings immediately, but I understand there's probably a tradeoff somewhere.  Reseting the fretboard isn't too big of a deal.  Thanks again for the free beta!
-Austin Jenkins  
     
    On Tuesday, June 30, 2020, 12:40:47 AM PDT, matkatmusic <notifications@github.com> wrote:  
 
 


I hope this clarifies things:
https://youtu.be/tG6DMDqmbHs

clicking on the keyboard is planned for later:
https://youtu.be/yBbtQyOTMTg
https://youtu.be/WbosKb3bBEA

**Comment by matkatmusic** [comment]
`it would be super helpful to have the option to instantly access the alternative voicings immediately`
I'm not sure what you mean by that.  
But the latest build lets you program your own voicings by clicking on the fretboard directly. 
See the video in the latest update I sent out last night.
