### ISSUE TITLE
Too many notes

### ISSUE THREAD

**Issue by ghost** [matkatmusic/ChordieApp_IssueTracker#62]
So i just realized that if it's to many notes then the fretboard is greyed out. Im not able to click the notes off, so besides resetting to default to clear the notes. Any other options?

<img width="1440" alt="Screen Shot 2020-07-02 at 07 54 45" src="https://user-images.githubusercontent.com/66919419/86356185-d15e5700-bc39-11ea-824f-4cf55fd19aee.png">

**Comment by matkatmusic** [comment]
Yeah, the 'all notes off' menu choice under 'options'.
