### ISSUE TITLE
Seems there is no way to disable the fretboard module

### ISSUE THREAD

**Issue by lcalder** [matkatmusic/ChordieApp_IssueTracker#68]
The fretboard preferences has a slider "Enable Fretboard Module" which is always grayed out (with it selected to ON)...

I tried turning all the other options on to see if I could access that option, but no...

On one of the various beta builds I was able to, but for a while now it hasn't been available. I also tried both reset options under the fretboard menu but still no.

**Comment by matkatmusic** [comment]
Reset settings to default
