### ISSUE TITLE
Many crashing Debug Assertion bugs in the latest Windows build

### ISSUE THREAD

**Issue by frauber84** [matkatmusic/ChordieApp_IssueTracker#7]
Function "Reset Fretboard to Default" crashes the program if:
1) more strings are added then clicking on an open string
2) strings are removed (less than 6) than clciking on an open string
3) when there is a fretboard position set then user removes strings (sorry, couldn't pinpoint exactly what triggers it)

Also, so far I'm testing without a MIDI input, but I find very odd how the keyboard interacts with the fretboard. If I click on a "blue" piano key and unset it, it doesn't disappear from the notation or from the fretboard. 

http://prntscr.com/szisj7

**Comment by matkatmusic** [comment]
Great, I'll investigate!

**Comment by matkatmusic** [comment]
Fixed in next build.
