### ISSUE TITLE
Chordie App not opening on Mac os Catalina

### ISSUE THREAD

**Issue by titocarrillo** [matkatmusic/ChordieApp_IssueTracker#72]
I recently purchased ChordieApp but hadn't tried to open and use it until today, and I got this prompt from Apple:

<img width="436" alt="Screen Shot 2020-07-28 at 9 27 06 AM" src="https://user-images.githubusercontent.com/68912517/88679739-5c096900-d0b5-11ea-9335-009ed46e237b.png">

It's a prompt saying "ChordieApp can't be opened because Apple cannot check it for malicious software.  The software needs to be updated.  Contact the developer for more information."

I want to start using this app to record online music tutorials.  Help!  Thanks,

Tito

**Comment by matkatmusic** [comment]
You need to update.  The app is Notarized now.  Check the FAQ for how to update https://www.chordieapp.com
