### ISSUE TITLE
Separate windows cannot be expanded / narrowed only horizontally or only vertically (Windows)

### ISSUE THREAD

**Issue by chordig** [matkatmusic/ChordieApp_IssueTracker#9]
When I turn on "Switch to separate windows":
a) the "piano roll" window cannot be expanded / narrowed only horizontally as in the previous version (only proportional resizing works)
b) the "chord names" window cannot be extended / narrowed only horizontally or only vertically as in the previous version (only proportional resizing works)
My system is Windows 8.1.

**Comment by matkatmusic** [comment]
This is intentional so that everything looks the same regardless of scale.  I need the grand staff and chord names to all look normal no matter the zoom size.

**Comment by chordig** [comment]
Maybe this could be possible although only for the Piano roll window. It would be very useful in arranging windows on the screen. In the previous version of the application it was very helpful.

**Comment by matkatmusic** [comment]
It'll be changed in a later version.
